config/routes.rb
Rails.application.routes.draw do  



  resources :users do
    collection do
      get 'login_form'
      post 'login'
      get 'logout'
    end
    member do
      get 'confirm'
      patch 'confirmed'
    end
  end

  resources :posts do
    collection do
      post 'confirm'
    end
    member do
      post 'dummy'
      patch 'edit_confirm'
      post 'commit'
    end
    
    resources :comments do
      collection do
        post 'confirm'
      end
      member do
        post 'dummy2'
      end  
    end
  end

  resource :answer, controller: 'answer', only: [:new, :create, :destroy] do
    collection do
      post 'answer_confirm'
    end

    resources :likes, only: [:create, :destroy]
  end

  get root 'home#top'

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/user.rb
class User < ApplicationRecord
<<<<<<< HEAD
  validates :name, {presence: true, uniqueness: true, length: {maximum: 30}}
  validates :email, {presence: true, uniqueness: true, length: {maximum: 30}}

  has_one_attached :avatar
=======
  before_save { self.email = email.downcase }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :name, presence: true, length: { maximum: 30 }
  validates :email, presence: true, length: { maximum: 30 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  validates :password, presence: true, length: { minimum: 4 }
  validates :avatar, presence: true
  has_secure_password

  has_one_attached :avatar

  def posts
    return Post.where(user_id: self.id)
  end
>>>>>>> main
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  layout 'default_layouts'
  before_action :require_login, only: [:edit, :index, :show, :destroy]
  before_action :forbid_login_user, only: [:new, :create, :login_form, :login]
  before_action :ensure_correct_user, only: [:edit, :update]


  def login_form
  end

  def login
    @user = User.find_by(email: params[:email].downcase)
    if @user && @user.authenticate(params[:password])
      session[:user_id] = @user.id
      redirect_to posts_path
    else
      @error_message = "メールアドレスまたはパスワードが間違っています"
      render login_form_users_path
    end
  end

  def logout
    session[:user_id] = nil
    @current_user = nil
    redirect_to root_path
  end

  def index
    @users = User.all.order(created_at: :desc)
  end

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
    @email_input_flg = nil
    @password_input_flg = nil
  end

  def create
    @user = User.new(user_params)
    if !@user.save
      render :new
    else
      redirect_to confirm_user_path(@user)
    end
  end

  def confirm
    @user = User.find(params[:id])
  end

  def confirmed
    @user = User.find(params[:id])
    if params[:back]
      @user.destroy
      render :new, status: :see_other
    else
      session[:user_id] = @user.id
      redirect_to user_path(@user)
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if !@user.update(user_params)
      render :edit
    else
      redirect_to user_path(@user)
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to root_path, status: :see_other
  end

  def ensure_correct_user
    if @current_user.id != params[:id].to_i
      redirect_to posts_path
    end
  end

  private
  def user_params
    params.require(:user).permit(:name, :email, :avatar, :password, :password_confirmation)
  end

end

app/helpers/users_helper.rb
module UsersHelper
  def current_user
    if session[:user_id]
      @current_user ||= User.find_by(id: session[:user_id])
    end
  end

  def logged_in?
    !current_user.nil?
  end

  def require_login
    redirect_to root_path if !logged_in?
  end

  def user_error_message_change(email_input_flg, password_input_flg, message)
    if message == 'Emailは不正な値です' && email_input_flg
      return nil
    end
    if message == 'Passwordは8文字以上で入力してください' && password_input_flg
      return nil
    end
    if message == 'Passwordを入力してください' && password_input_flg
      return nil
    end
    if message == 'Password confirmationとPasswordの入力が一致しません'
      return 'Passwordの値が一致しません'
    end
    if message == 'Avatarを入力してください'
      return 'アイコン画像を選択してください'
    end
    return message
  end

end

app/views/users/confirm.html.erb
<div class="page-title">
  <h3>登録情報確認</h3>
</div>

<div class="user-confirm-item">
  <div class="container">
    <div class="users-show-item">
      <div class="user-image">
        <% if @user.avatar.attached? %>
          <%= image_tag @user.avatar %>
        <% end %>
      </div>
      <div class="user-name">
        <p><%= @user.name %></p>
      </div>
      <div class="email">
        <p><%= @user.email %></p>
      </div>
    </div>

    <%= form_with model: @user, url: confirmed_user_path(@user), data: { turbo: false } do |form| %>
      <%= form.hidden_field :name %>
      <%= form.hidden_field :email %>
      <%= form.hidden_field :avatar %>
      <%= form.submit "登録", class: "button1" %>
      <%= form.submit "修正", name: "back", class: "button1" %>
    <% end %>
  </div>
</div>

app/views/users/edit.html.erb
<div class="page-title">
  <h3>登録情報変更</h3>
</div>

<%= form_with model: @user, data: { turbo: false } do |form| %>
  <div class="main users-new">
    <div class="container">
      <div class="text-field-group-users">
        <%= form.label :name, "ユーザー名" %>
        <%= form.text_field :name, class: "users-text-field" %>
      </div>
      <div class="text-field-group-users">
        <%= form.label :email, "E-mail" %>
        <%= form.text_field :email, class: "users-text-field" %>
      </div>
      <div class="login-field-group">
        <%= form.label :password %>
        <%= form.password_field :password, class: "users-login-field" %>
      </div>
      <div class="login-field-group">
        <%= form.label :password_confirmation, 'password(確認)' %>
        <%= form.password_field :password_confirmation, class: "users-login-field" %>
      </div>
      <div class="file-field-group">
        <%= form.label :avatar, "アイコン画像" %>
        <%= form.file_field :avatar, class: "users-file-field" %>
      </div>
      <div>
        <%= form.submit "登録", class: "button1" %>
      </div>
      
      <% @user.errors.full_messages.each do |message| %>
        <div class="form-error">    
          <% message = user_error_message_change(@email_input_flg, @password_input_flg, message) %>
          <% if message %>
            <%= "#{message}。" %>
          <% end %>

          <% if message == 'Emailを入力してください' %>  
            <% @email_input_flg = true %>
          <% end %>
          <% if message == 'Passwordを入力してください' %>
            <% @password_input_flg = true %>
          <% end %>
        </div>
      <% end %>
    </div>
  </div>
<% end %>

<div class="turn-back">
  <%= link_to '戻る', user_path(@user), data: { turbo: false }, class: 'return' %>
</div>

app/views/users/index.html.erb
<div class="page-title">
  <h3>ユーザー一覧</h3>
</div>

<div class="main users-index">
  <div class="container">
    <% @users.each do |user| %>
      <div class="users-index-item">
        <div class="index-user-image">
          <%= image_tag user.avatar %>
        </div>
        <%= link_to "#{user.name}", user_path(user), data: { turbo: false }, class: "index-item2" %>
      </div>
    <% end %>
  </div>
</div>

app/views/users/login_form.html.erb
<div class="page-title">
  <h3>ログインフォーム</h3>
</div>

<%= form_with url: login_users_path, data: { turbo: false } do |form| %>
  <div class="main login-form">
    <div class="container">
      <div class="login-field-group">
        <%= form.label :email, "E-mail" %>
        <%= form.text_field :email, class: "users-login-field" %>
      </div>
      <div class="login-field-group">
        <%= form.label :password %>
        <%= form.password_field :password, class: "users-login-field" %>
      </div>
      <div>
        <%= form.submit "ログイン", class: "button1" %>
      </div>
      
      <div class="form-error">
        <%= @error_message %>
      </div>
    </div>
  </div>
<% end %>

<div class="turn-back">
  <%= link_to '戻る', root_path, data: { turbo: false }, class: 'return' %>
</div>

app/views/users/new.html.erb
<div class="page-title">
  <h3>ユーザー登録</h3>
</div>

<%= form_with model: @user, data: { turbo: false } do |form| %>
  <div class="main users-new">
    <div class="container">
      <div class="text-field-group-users">
        <%= form.label :name, "ユーザー名" %>
        <%= form.text_field :name, class: "users-text-field" %>
      </div>
      <div class="text-field-group-users">
        <%= form.label :email, "E-mail" %>
        <%= form.text_field :email, class: "users-text-field" %>
      </div>
      <div class="login-field-group">
        <%= form.label :password %>
        <%= form.password_field :password, class: "users-login-field" %>
      </div>
      <div class="login-field-group">
        <%= form.label :password_confirmation, 'password(確認)' %>
        <%= form.password_field :password_confirmation, class: "users-login-field" %>
      </div>
      <div class="file-field-group">
        <%= form.label :avatar, "アイコン画像" %>
        <%= form.file_field :avatar, class: "users-file-field" %>
      </div>
      <div>
        <%= form.submit "登録", class: "button1" %>
      </div>
      
      <% @user.errors.full_messages.each do |message| %>
        <div class="form-error">    
          <% message = user_error_message_change(@email_input_flg, @password_input_flg, message) %>
          <% if message %>
            <%= "#{message}。" %>
          <% end %>

          <% if message == 'Emailを入力してください' %>  
            <% @email_input_flg = true %>
          <% end %>
          <% if message == 'Passwordを入力してください' %>
            <% @password_input_flg = true %>
          <% end %>
        </div>
      <% end %>
    </div>
  </div>
<% end %>

<div class="turn-back">
  <%= link_to '戻る', root_path, data: { turbo: false }, class: 'return' %>
</div>

app/views/users/show.html.erb
<div class="page-title">
  <h3>ユーザー詳細</h3>
</div>

<div class="main user-show">
  <div class="container">
    <div class="users-show-item">
      <div class="user-image">
        <%= image_tag @user.avatar %>
      </div>
      <div class="user-name"> 
        <p><%= @user.name %></p>
      </div>
      <div class="token">
        <span class="fa-solid fa-coins"></span>
        <p>トークン数</p>
        <p><%= @user.token %></p>
      </div>
      <div class="evaluation">
        <span class="fa-solid fa-star"></span>
        <p>評価</p>
        <p><%= @user.evaluation %></p>
      </div>
      <% if @user.id == @current_user.id %>
        <div class="email">
          <p><%= @user.email %></p>
        </div>
        <div class="users-menus">
          <%= link_to '編集', edit_user_path, data: { turbo: false }, class: 'user-menu' %>
          <div class="user-menu" id="eliminate">
            退会
          </div>
        </div>
      <% end %>
    </div>
    
    <div class="users-show-item2">
      <% @user.posts.each do |post| %>
        <div class="posts-index-item2">
          <div class="posts-index-user-image2">
            <%= image_tag post.user.avatar %>
          </div>
          <div class="posts-index-user-name2">
            <%= post.user.name %>
          </div>
          <%= link_to "#{post.title}", post_path(post), data: { turbo: false }, class: "index-item3" %>
        </div>
      <% end %>
    </div>
    <div class="turn-back">
    <%= link_to '戻る', users_path, data: { turbo: false }, class: 'return' %>
    </div>
  </div>
</div>

<div id="mask" class="hidden2"></div>

<section id="modal" class="hidden2">
  <p>本当に退会してもよろしいですか？</p>
  <div class="buttons">
    <div id="del" class="link_del">
      <%= link_to '退会', "/users/#{@user.id}", data: { turbo_method: :delete }, class: 'button2' %>
    </div>
    <div id="cancel" class="button1">
      中止
    </div>
  </div>
</section>