config/routes.rb
Rails.application.routes.draw do  



  resources :users do
    collection do
      get 'login_form'
      post 'login'
      get 'logout'
    end
    member do
      get 'confirm'
      patch 'confirmed'
    end
  end

  resources :posts do
    collection do
      post 'confirm'
    end
    member do
      post 'dummy'
      patch 'edit_confirm'
      post 'commit'
    end
    
    resources :comments do
      collection do
        post 'confirm'
      end
      member do
        post 'dummy2'
      end  
    end
  end

  resource :answer, controller: 'answer', only: [:new, :create, :destroy] do
    collection do
      post 'answer_confirm'
    end

    resources :likes, only: [:create, :destroy]
  end

  get root 'home#top'

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/answer.rb
class Answer < ApplicationRecord
  has_many :likes, dependent: :destroy
  belongs_to :post
end

app/controllers/answer_controller.rb
class AnswerController < ApplicationController
  layout 'default_layouts'

  def new
    @post = Post.find_by(id: params[:post_id])
    @answer = @post.build_answer
  end

  def answer_confirm
    @answer = Answer.new(answer_params)
    render :new if @answer.invalid?
  end

  def create
    @answer = Answer.new(answer_params)
    @post = @answer.post
    if params[:back] || !@answer.save
      render :new
    else
      redirect_to post_path(@post)
    end
  end

  def destroy
    @post = Post.find_by(id: params[:post_id])
    @post.answer.destroy
    @post.commit = nil
    @post.save!
    redirect_to post_path(@post)
  end

  private
  def answer_params
    params.require(:answer).permit(:content, :post_id, :user_id)
  end

end

app/helpers/answer_helper.rb
module AnswerHelper
end

app/views/answer/_answer.html.erb
<% if post.answer.presence %>
  <div class="answer-show-item">
    <div class="posts-user-image">
      <%= image_tag  answer_user.avatar %>
    </div>
    <div class="posts-user-name"> 
      <%=  answer_user.name %>
    </div>
    <div class="posts-title">
      <p><%= '回答' %></p>
    </div>
    <div class="posts-content">
      <%= safe_join(post.answer.content.split("\n"),tag(:br)) %>
    </div>

    <div class="posts-time">
      <%= post.updated_at.strftime("%Y-%m-%d %H:%M:%S") %>
    </div>

    <%= turbo_frame_tag "liketag" do %>
      <% if like.presence %>
        <%= button_to answer_like_path(like), method: :delete, params: { post_id: post.id } do %>
          <i class="fa-solid fa-heart like-btn", id="like_button"></i>
        <% end %>
      <% else %>
        <%= button_to answer_likes_path, params: { post_id: post.id } do %>
          <i class="fa-solid fa-heart dislike-btn", id="like_button"></i>
        <% end %>
      <% end %>
      <p><%= likes_count %></p>
    <% end %>

    <div class="posts-menus">
      <% if post.answer.user_id == @current_user.id %>
        <div class="edit-menu" >
          <%= button_to '削除', dummy_post_path(post), class: 'destroy-modal button5' %>
        </div>
      <% end %>
    </div>
  </div>
<% end %>

app/views/answer/answer_confirm.html.erb
<div class="page-title">
  <h3>回答内容確認</h3>
</div>

<div class="confirm-item">
  <div class="container">
    <div class="confirm-content">
      <%= safe_join(@answer.content.split("\n"),tag(:br)) %>
    </div>
    
    <%= form_with( model: @answer, url: "/answer", data: { turbo: false }) do |form| %>
      <%= form.hidden_field :content %>
      <%= form.hidden_field :post_id, value: @answer.post_id %>
      <%= form.hidden_field :user_id, value: @current_user.id %>
      <%= form.submit "投稿", class: "button1" %>
      <%= form.submit "修正", name: "back", class: "button1" %>
    <% end %>
  </div>
</div>

app/views/answer/new.html.erb
<div class="page-title">
  <h3>回答投稿</h3>
</div>

<%= form_with(model: @answer, url: answer_confirm_answer_path, data: { turbo: false }) do |form| %>
  <div class="main answer-new">
    <div class="container">
      <%= form.hidden_field :post_id, value: @post.id %>
      <%= form.hidden_field :user_id, value: @current_user.id %>
      <div class="text-area-group2">
        <%= form.label :content, "回答" %>
        <%= form.text_area :content, class: "text-area2" %>
      </div>
      <div>
        <%= form.submit "投稿", class: "button1" %>
      </div>
      
      <% @answer.errors.full_messages.each do |message| %>
        <div class="form-error2">
          <%= message %>
        </div>
      <% end %>
    </div>
  </div>
<% end %>

<div class="turn-back">
  <%= link_to '戻る', "/posts/#{@answer.post_id}", data: { turbo: false }, class: 'return' %>
</div>