config/routes.rb
Rails.application.routes.draw do  



  resources :users do
    collection do
      get 'login_form'
      post 'login'
      get 'logout'
    end
    member do
      get 'confirm'
      patch 'confirmed'
    end
  end

  resources :posts do
    collection do
      post 'confirm'
    end
    member do
      post 'dummy'
      patch 'edit_confirm'
      post 'commit'
    end
    
    resources :comments do
      collection do
        post 'confirm'
      end
      member do
        post 'dummy2'
      end  
    end
  end

  resource :answer, controller: 'answer', only: [:new, :create, :destroy] do
    collection do
      post 'answer_confirm'
    end

    resources :likes, only: [:create, :destroy]
  end

  get root 'home#top'

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/post.rb
class Post < ApplicationRecord
  has_one :answer, dependent: :destroy
  has_many :comments, dependent: :destroy

  validates :title, { presence: true, length: {maximum: 50} }
  validates :content, { presence: true, length: {maximum: 3000} }
  validates :user_id, { presence: true }
  validates :reward, { presence: true }

  def user
    return User.find_by(id: self.user_id)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  layout 'default_layouts'
  before_action :require_login, only: [:confirm, :edit, :index, :new, :show, :commit]
  before_action :ensure_correct_post_user, only: [:edit, :update, :destroy]

  def index
      @posts = Post.all.order(created_at: :desc)
  end

  def show
    @post = Post.find(params[:id])
    @user = @post.user
    @comments = @post.comments
    @like = nil
    @likes_count = 0
    @tcid = 0

    if @post.answer.presence
      @answer = @post.answer
      @answer_user = User.find_by(id: @answer.user_id)

      if @answer.likes.presence
        @likes_count = @answer.likes.count
        @like = @post.answer.likes.find_by(user_id: @current_user.id)
      end  
    end
  end

  def new
    @post = Post.new(user_id: @current_user.id)
  end

  def confirm
    @post = Post.new(post_params)
    @post.user_id = @current_user.id
    render :new if @post.invalid?
  end
  
  def create
    @post = Post.new(post_params)
    @post.user_id = @current_user.id
    if params[:back] || !@post.save
      render :new
    else
      redirect_to action: :index
    end
  end

  def edit
    @post = Post.find(params[:id])
  end

  def edit_confirm
    @post = Post.find(params[:id])
    @post.attributes = post_params
    render :edit if @post.invalid?
  end

  def update
    @post = Post.find(params[:id])
    if params[:back] || !@post.update(post_params)
      render :edit
    else
      redirect_to post_path(@post)
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to posts_path, status: :see_other
  end

  def commit
    @post = Post.find(params[:id])

    if !@post.commit
      @post.commit = @current_user.id
    else
      @post.commit = nil
    end
    @post.save!
  end

  def ensure_correct_post_user
    @post = Post.find_by(id: params[:id])
    if @post.user_id != @current_user.id
      redirect_to posts_path
    end
  end

  def dummy
  end

  private
  def post_params
    params.require(:post).permit(:title, :content, :user_id, :reward, :commit)
  end

end

app/helpers/posts_helper.rb
module PostsHelper
  def post_error_message_change(message)
    if message == 'Rewardを入力してください'
      return '報酬額を入力してください'
    end
    return message
  end

end

app/views/posts/answer.html.erb
<div class="page-title">
  <h3>回答投稿</h3>
</div>

<%= form_with model: @answer, url: answer_confirm_post_path(@post), data: { turbo: false }  do |form| %>
  <div class="main answer-new">
    <div class="container">
      <%= form.hidden_field :post_id, value: @post.id %>
      <%= form.hidden_field :user_id, value: @current_user.id %>
      <div class="text-area-group2">
        <%= form.label :content, "回答" %>
        <%= form.text_area :content, class: "text-area2" %>
      </div>
      <div>
        <%= form.submit "投稿", class: "button1" %>
      </div>
      
      <% @answer.errors.full_messages.each do |message| %>
        <div class="form-error2">
          <%= message %>
        </div>
      <% end %>
    </div>
  </div>
<% end %>

<div class="turn-back">
  <%= link_to '戻る', "/posts/#{@answer.post_id}", data: { turbo: false }, class: 'return' %>
</div>

app/views/posts/answer_confirm.html.erb
<div class="page-title">
  <h3>回答内容確認</h3>
</div>

<div class="confirm-item">
  <div class="container">
    <div class="confirm-content">
      <%= safe_join(@answer.content.split("\n"),tag(:br)) %>
    </div>
    
    <%= form_with model: @answer, url: answer_create_post_path(@post), data: { turbo: false } do |form| %>
      <%= form.hidden_field :content %>
      <%= form.hidden_field :post_id %>
      <%= form.hidden_field :user_id %>
      <%= form.submit "投稿", class: "button1" %>
      <%= form.submit "修正", name: "back", class: "button1" %>
    <% end %>
  </div>
</div>

app/views/posts/confirm.html.erb
<div class="page-title">
  <h3>投稿内容確認</h3>
</div>

<div class="confirm-item">
  <div class="container">
    <div class="posts-title">
  
      <%= @post.title %>
    </div>
    <div class="confirm-reward">
      <%= "報酬額: #{@post.reward}" %>
    </div>
    <div class="confirm-content">
      <%= safe_join(@post.content.split("\n"),tag(:br)) %>
    </div>

    <%= form_with model: @post, data: { turbo: false } do |form| %>
      <%= form.hidden_field :title %>
      <%= form.hidden_field :reward %>
      <%= form.hidden_field :content %>
      <%= form.submit "投稿", class: "button1" %>
      <%= form.submit "修正", name: "back", class: "button1" %>
    <% end %>
  </div>
</div>

app/views/posts/edit.html.erb
<div class="page-title">
  <h3>投稿編集</h3>
</div>

<%= form_with model: @post, data: { turbo: false } do |form| %>
  <div class="main posts-new">
    <div class="container">      
      <div class="text-field-group">
        <%= form.label :title, "タイトル" %>
        <%= form.text_field :title, class: "text-field" %>
      </div>
      <div class="number-field-group">
        <%= form.label :reward, "　報酬額" %>
        <%= form.number_field :reward, min: 1000, max: 50000, step: 1000, class: "number-field" %>
      </div>
      <div class="text-area-group">
        <%= form.label :content, "依頼内容" %>
        <%= form.text_area :content, class: "text-area" %>
      </div>
      <div>
        <%= form.submit "投稿", class: "button1" %>
      </div>
      
      <% @post.errors.full_messages.each do |message| %>
        <div class="form-error">
          <% message = post_error_message_change(message) %>
          <% if message %>
            <%= "#{message}。" %>
          <% end %>
        </div>
      <% end %>
    </div>
  </div>
<% end %>

<div class="turn-back">
  <%= link_to '戻る', post_path, data: { turbo: false }, class: 'return' %>
</div>

app/views/posts/edit_confirm.html.erb
<div class="page-title">
  <h3>編集内容確認</h3>
</div>

<div class="confirm-item">
  <div class="container">
    <div class="posts-title">
      <%= @post.title %>
    </div>
    <div class="confirm-reward">
      <%= "報酬額: #{@post.reward}" %>
    </div>
    <div class="confirm-content">
      <%= safe_join(@post.content.split("\n"),tag(:br)) %>
    </div>
    
    <%= form_with model: @post, data: { turbo: false } do |form| %>
      <%= form.hidden_field :title %>
      <%= form.hidden_field :reward %>
      <%= form.hidden_field :content %>
      <%= form.submit "確定", class: "button1" %><%= form.submit "修正", name: "back", class: "button1" %>
    <% end %>
  </div>
</div>

app/views/posts/index.html.erb
<div class="page-title">
  <h3>質問一覧</h3>
</div>

<div class="main posts-index">
  <div class="container">
    <% @posts.each do |post| %>
      <div class="posts-index-item">
        <div class="posts-index-user-image">
          <%= image_tag post.user.avatar %>
        </div>
        <div class="posts-index-user-name">
          <%= post.user.name %>
        </div>
        <%= link_to "#{post.title}", post_path(post), data: { turbo: false }, class: "index-item" %>
        <div class="posts-index-reward">
          <%= "報酬額: #{post.reward}" %>
        </div>
        <% if post.answer %>
          <div class="posts-index-committed">
            <p>解決済</p>
          </div>
        <% else %>
          <div class="posts-index-commit">
            <p>未解決</p>
          </div>
        <% end %>
      </div>
    <% end %>
  </div>
</div>

app/views/posts/new.html.erb
<div class="page-title">
  <h3>質問投稿</h3>
</div>

<%= form_with model: @post, url: confirm_posts_path(@post), data: { turbo: false } do |form| %>
  <div class="main posts-new">
    <div class="container">
      <div class="text-field-group">
        <%= form.label :title, "タイトル" %>
        <%= form.text_field :title, class: "text-field" %>
      </div>
      <div class="number-field-group">
        <%= form.label :reward, "　報酬額" %>
        <%= form.number_field :reward, min: 1000, max: 50000, step: 1000, class: "number-field" %>
      </div>
      <div class="text-area-group">
        <%= form.label :content, "依頼内容" %>
        <%= form.text_area :content, class: "text-area" %>
      </div>
      <div>
        <%= form.submit "投稿", class: "button1" %>
      </div>
      
      <% @post.errors.full_messages.each do |message| %>
        <div class="form-error">
          <%= message %>
        </div>
      <% end %>
    </div>
  </div>
<% end %>

<div class="turn-back">
  <%= link_to '戻る', posts_path, data: { turbo: false }, class: 'return' %>
</div>

app/views/posts/show.html.erb
<div class="page-title">
  <h3>質問詳細</h3>
</div>

<% ### 質問詳細　############################################################################## %>

<div class="main posts-show">
  <div class="container">
    <div class="posts-show-item">
      <div class="posts-user-image">
        <%= image_tag @user.avatar %>
      </div>
      <div class="posts-user-name"> 
        <%= @user.name %>
      </div>
      <div class="show-reward">
        <%= "報酬額: #{@post.reward}" %>
      </div>
      <div class="posts-title">
        <%= @post.title %>
      </div>
      <div class="posts-content">
        <%= safe_join(@post.content.split("\n"),tag(:br)) %>
      </div>
      <div class="posts-time">
        <%= @post.updated_at.strftime("%Y-%m-%d %H:%M:%S") %>
      </div>



      <div class="posts-menus">
        <% if @post.user_id == @current_user.id %>
          <div class="edit-menu">
            <%= link_to '編集', edit_post_path, data: { turbo_method: :get }, class: 'button1' %>
          </div>
          <div class="edit-menu" >
            <%= button_to '削除', dummy_post_path(@post), class: 'destroy-modal button5' %>
          </div>
        <% else %>
          <% if @post.answer.presence %>
            <div class="edit-menu">
              <%= link_to '回答済み', "#", id: 'commit_button', class: 'button4' %>
            </div>
            <div class="edit-menu">
              <%= button_to '回答', '#', id: 'answer_button', class: 'button4' %>
            </div>
          <% elsif !@post.commit %>
            <div class="edit-menu">
              <%= button_to 'コミット', commit_post_path(@post), id: 'commit_button', class: 'button3 lighten' %>
            </div>
            <div class="edit-menu">
              <%= link_to '回答', new_answer_path(post_id: @post.id), id: 'answer_button', class: 'button4' %>
            </div>
          <% elsif @post.commit == @current_user.id %>
            <div class="edit-menu">
              <%= button_to 'コミット解除', commit_post_path(@post), id: 'commit_button', class: 'button3' %>
            </div>
            <div class="edit-menu">
              <%= link_to '回答', new_answer_path(post_id: @post.id), id: 'answer_button', class: 'button1' %>
            </div>
          <% else %>
            <div class="edit-menu">
              <%= button_to 'コミット解除', "#", id: 'commit_button', class: 'button4' %>
            </div>
            <div class="edit-menu">
              <%= button_to '回答', '#', id: 'answer_button', class: 'button4' %>
            </div>
          <% end %>
          <div class="edit-menu">
            <%= button_to '返信', new_post_comment_path(@post), method: :get, class: 'button1' %>
          </div>
        <% end %>
      </div>
    </div>


<%#### 回答　########################################################################### %>
    
    <%= render partial: "/answer/answer", locals: { post: @post, like: @like, answer_user: @answer_user, likes_count: @likes_count } %>

<%#### 返信　########################################################################### %>

    <%= render partial: "/comments/comment", collection: @comments, locals: { post: @post } %>

    <%= "tcID=#{@tcid}" %>

    <div class="turn-back">
      <%= link_to '戻る', posts_path, data: { turbo: false }, class: 'return' %>
    </div>
  </div>
</div>

<div id="mask" class="hidden2"></div>

<section id="modal" class="hidden2">
  <p>本当に削除してよろしいですか？</p>
  <div class="buttons">
    <div id="del">
      <% if @post.user_id == @current_user.id then %>
        <%= button_to '削除', post_path(@post), method: :delete, data: { turbo: false }, class: 'button2' %>
      <% elsif @target_comment then %>
        <%= "target_comment=#{@target_comment.id}" %>
        <%= button_to '削除', "/posts/#{@post.id}/comments/#{@target_comment.id}", method: :delete, data: { turbo: false }, class: 'button2' %>
      <% end %>
    </div>
    <div id="cancel">
      <p class="button1"><% @target_comment %></p>
    </div>
  </div>
</section>