config/routes.rb
Rails.application.routes.draw do  



  resources :users do
    collection do
      get 'login_form'
      post 'login'
      get 'logout'
    end
    member do
      get 'confirm'
      patch 'confirmed'
    end
  end

  resources :posts do
    collection do
      post 'confirm'
    end
    member do
      post 'dummy'
      patch 'edit_confirm'
      post 'commit'
    end
    
    resources :comments do
      collection do
        post 'confirm'
      end
      member do
        post 'dummy2'
      end  
    end
  end

  resource :answer, controller: 'answer', only: [:new, :create, :destroy] do
    collection do
      post 'answer_confirm'
    end

    resources :likes, only: [:create, :destroy]
  end

  get root 'home#top'

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RentalBrain</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags("home") %>
    <script src="https://kit.fontawesome.com/be4e22ccae.js" crossorigin="anonymous"></script>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/layouts/default_layouts.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RentalBrain</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags("application") %>
    <script src="https://kit.fontawesome.com/be4e22ccae.js" crossorigin="anonymous"></script>
  </head>

  <body>
    <div class="header0">
      <div class="header-logo">
        <%= link_to 'RentalBrain', root_path, class: "header-link1", data: { turbo: false } %>
      </div>
      <ul class="header-menus">
        <% if @current_user %>
          <li>
            <%= link_to "#{@current_user.name}さん", user_path(@current_user), data: { turbo: false }, class: "header-link2" %>
          </li>
          <li>
            <%= link_to '質問投稿', new_post_path, data: { turbo: false }, class: "header-link2" %>
          </li>
          <li>
            <%= link_to '質問一覧', posts_path, data: { turbo: false }, class: "header-link2" %>
          </li>
          <li>
            <%= link_to '回答者一覧', users_path, data: { turbo: false }, class: "header-link2" %>
          </li>
          <li>
            <%= link_to 'ログアウト', logout_users_path, data: { turbo: false }, class: "header-link2" %>
          </li>
        <% end %>
      </ul>
    </div>

    <%= yield %>
  </body>
</html>